/* Lychee-FD 页面统一配置 */

window.LYCHEE_CONFIG = {
  site: {
    title: "Lychee-FD",
    subtitle: "",
    slogan: "Native end-to-end full-duplex spoken language model for real-time speech interaction.",
    description: "Lychee-FD is a native end-to-end full-duplex spoken language model. It addresses modality interference and semantic dilution through hierarchical acoustic-semantic modeling, and supports low-latency online inference, digital avatar demos, and robot interaction demos.",
    brand: "Lychee-FD",
    brandSub: "Native full-duplex SLM",
  },

  navigation: [
    { label: "Overview", target: "hero" },
    { label: "Technical blog", target: "technology" },
    { label: "Results", target: "results" },
    { label: "Demos", target: "demo" },
  ],

  heroPills: [],

  heroPromoVideo: {
    title: "Lychee-FD interaction demo",
    video: "assets/videos/xuanchuan.mp4",
    poster: "assets/images/demo/xuanchuan-poster.jpg",
    preload: "none",
    autoplay: false,
    muted: true,
    loop: false,
    playsinline: true,
  },

  metrics: [
    { value: "+7.4%", label: "Spoken QA average improvement", note: "Speech intelligence" },
    { value: "+28.5%", label: "FullDuplexBench 1.5 improvement", note: "Interaction fluency" },
    { value: "-11.2%", label: "Interruption response latency reduction", note: "Timely response" },
    { value: "2.96×", label: "RTF speedup with multi-stream inference", note: "Engineering efficiency" },
  ],

  problemSection: {
    sectionIndex: "技术介绍 02 / 科学问题",
    title: "为什么过去的语音交互总是不自然？",
    intro: [
      {
        segments: [
          { text: "过去的语音 AI，大多仍运行在" },
          { text: "轮次交互", strong: true },
          { text: "的范式里：用户先说完，系统再识别、理解、生成、播报。它可以完成问答，但很难形成真正自然的交流。" },
        ],
      },
      {
        segments: [
          { text: "后来，一些系统开始尝试全双工交互：在传统语音链路外部增加打断检测、状态判断和调度模块，让 AI 看起来可以边听边说。但这种" },
          { text: "系统级全双工", strong: true },
          { text: "本质上仍然是多个模块在外部协作，容易带来额外延迟、轮次切换生硬和语义表达割裂。" },
        ],
      },
    ],
    figure: {
      title: "三类语音交互路线对比",
      src: "assets/images/paper/full_duplex_route_compare_en.png",
      width: 1130,
      height: 624,
      alt: "半双工语音 AI、系统级全双工与原生端到端全双工的对比图",
    },
    routeCards: [
      {
        label: "Legacy",
        title: "半双工语音 AI",
        text: "ASR、LLM、TTS 串行执行，系统通常要等用户说完再回答，轮次感强，插话处理困难。",
      },
      {
        label: "Cascade",
        title: "系统级全双工",
        text: "通过 VAD、Scheduler 等外部模块拼接打断与调度能力，可以处理部分插话，但链路仍然割裂。",
      },
      {
        label: "Lychee-FD",
        title: "原生端到端全双工",
        text: "把持续倾听、语义理解、语音生成和节奏控制统一注入模型内部，让交互能力在连续语音流中自然涌现。",
      },
    ],
    conclusion: {
      title: "Lychee-FD 的不同路线",
      paragraphs: [
        {
          segments: [
            { text: "Lychee-FD 不是在旧系统外面叠加“打断”“附和”“接话”等单点功能，而是让模型在持续倾听的同时，实时理解、实时生成、实时控制对话节奏。" },
          ],
        },
        {
          segments: [
            { text: "真正困难的不是简单边听边说，而是模型既要保留大语言模型的理解和推理能力，又要生成自然语音，并在连续对话中判断何时倾听、何时回应、何时停止输出。" },
          ],
        },
      ],
    },
    callout: {
      segments: [
        { text: "因此，过去语音交互不自然的根因，不只是工程模块不够多，而是听、想、说、控被拆散在外部链路里；Lychee-FD 的目标，是把这些能力内化为模型的原生交互能力。" },
      ],
    },
  },

  researchPath: {
    sectionIndex: "Technical blog 02 / Scientific insight",
    title: "Why native full-duplex is hard",
    description: "Native full-duplex SLMs must listen and speak at the same time while preserving semantic reasoning. Lychee-FD first demonstrates that the root cause is the inherent gradient conflict between acoustic rendering and semantic modeling within a shared parameter space.",
    groups: [
      {
        id: "scienceProblems",
        type: "figurePair",
        modules: [
          {
            kicker: "01 ",
            title: "Modality Conflict",
            description: "When acoustic generation and semantic modeling share the same deep parameter space, shallow layers can still be synergistic, but deeper layers show conflicting optimization directions. This explains why native full-duplex models struggle to be intelligent, natural, and low-latency at the same time.",
            figure: {
              title: "Modality interference",
              slotLabel: "Original Figure Slot",
              placeholder: "Replace this slot with the modality interference figure.",
              src: "assets/images/paper/modality_layer_conflict.png",
              width: 1746,
              height: 1153,
              alt: "Modality interference figure",
            },
          },
          {
            kicker: "02 ",
            title: "Semantic Dilution",
            description: "Speech tokens are much denser than text tokens. Conventional alignment can dilute sparse textual supervision with high-frequency acoustic frames, making the model biased toward reproducing speech while weakening semantic reasoning.",
            figure: {
              title: "Semantic dilution",
              slotLabel: "Original Figure Slot",
              placeholder: "Replace this slot with the semantic dilution figure.",
              src: "assets/images/paper/semantic_layer_sparsity.png",
              width: 1745,
              height: 1452,
              alt: "Semantic dilution figure",
            },
          },
        ],
      },
      {
        id: "architectureSolution",
        type: "solutionPlaceholder",
        kicker: "Technical blog 03 / Method",
        title: "Hierarchical acoustic-semantic modeling",
        leadParagraphs: [
          {
            segments: [
              { text: "Guided by the two findings above, Lychee-FD is designed around a simple principle: unify the interaction streams when possible, separate conflicting objectives when necessary, and keep the system efficient enough for real-time full-duplex speech interaction." },
            ],
          },
        ],
        points: [
          {
            label: "Native",
            title: "Native end-to-end full-duplex architecture",
            text: "Instead of a cascaded ASR-LLM-TTS pipeline, Lychee-FD unifies text, speech, and control channels for efficient inference and native conversational behavior.",
          },
          {
            label: "Separate",
            title: "Hierarchical acoustic-semantic parameter separation",
            text: "Deep semantic and acoustic parameters are physically decoupled to remove modality gradient conflicts while preserving inference efficiency and representational robustness.",
          },
          {
            label: "Align",
            title: "Dense semantic alignment channel",
            text: "Frame-level dense text streams serve as explicit semantic anchors, counteracting semantic dilution and preserving logical coherence and semantic consistency.",
          },
          {
            label: "Inference",
            title: "Real-time inference",
            text: "Multi-channel streaming generation is supported by customized vLLM inference, KV-cache reuse, and context management to reduce full-duplex interaction latency.",
          },
        ],
        detail: {},
        note: "",
        figure: {
          title: "Lychee-FD architecture",
          slotLabel: "Architecture Figure Slot",
          placeholder: "Place the Lychee-FD architecture figure under assets/images/architecture/ and set figure.src in config.js.",
          src: "assets/images/architecture/lychee_fd_architecture.png",
          width: 1436,
          height: 807,
          alt: "Lychee-FD architecture with shared backbone and semantic, acoustic, and control heads",
        },
      },
    ],
  },

  imageAssets: {
    spokenQATable: {
      id: "spokenQATable",
      title: "Spoken QA benchmark",
      src: "assets/images/charts/lychee_spoken_qa_table.svg",
      width: 1900,
      height: 1120,
      type: "image",
      section: "Results",
      tags: [],
      enabled: true,
      description: "",
      noteTitle: "Spoken question answering",
      resultNotes: [
        "Lychee-FD achieves the best average speech-to-speech accuracy among native full-duplex models, reaching 46.2 on S-S Avg. and outperforming the half-duplex StepAudio-2-mini baseline by 5.3 points.",
        "The ablations verify the design: removing the semantic alignment channel weakens knowledge retention, while removing hierarchical parameter separation causes a large drop in speech-to-speech accuracy.",
        "Overall, Lychee-FD improves Spoken QA performance by 7.4% while preserving the native full-duplex interaction setting."
      ],
    },
    duplexBenchTable: {
      id: "duplexBenchTable",
      title: "Full-duplex interaction benchmark",
      src: "assets/images/charts/lychee_duplex_bench_table.svg",
      width: 1900,
      height: 880,
      type: "image",
      section: "Results",
      tags: [],
      enabled: true,
      description: "",
      noteTitle: "Full-duplex interaction",
      resultNotes: [
        "Lychee-FD achieves strong performance across interruption, backchannel, turn-taking, and latency metrics, showing that native full-duplex modeling improves interaction fluency rather than only answering accuracy.",
        "On FullDuplexBench 1.5, Lychee-FD improves the overall interaction capability by 28.5%, while also reducing interruption response latency by 11.2%.",
        "These results show that Lychee-FD improves real-time full-duplex interaction quality across both behavior metrics and latency-sensitive settings."
      ],
    },
    onlineMultistreamInference: {
      id: "onlineMultistreamInference",
      title: "Online multi-stream inference speedup",
      src: "assets/images/architecture/online_multistream_inference.png",
      width: 1080,
      height: 612,
      type: "image",
      section: "Results",
      tags: [],
      enabled: true,
      description: "",
      noteTitle: "Online multi-stream inference",
      resultNotes: [
        "Compared with the HuggingFace baseline, the customized multi-stream vLLM inference framework reduces RTF from 1.94 to 0.65, achieving about 2.96× speedup.",
        "The same inference framework reduces GPU memory usage from 100% to 77%, saving approximately 23% memory and improving deployment efficiency for online full-duplex interaction."
      ],
    },
    avatarStatic: {
      id: "avatarStatic",
      title: "数字人展示",
      type: "image",
      section: "Lychee-FD 驱动数字人与机器人效果图",
      tags: ["Demo of Digital Avatar", "数字人"],
      enabled: true,
      src: "assets/images/avatar/avatar_static.png",
      width: 1024,
      height: 768,
      description: "Lychee-FD 驱动数字人形成自然语音、表情和口型联动。",
    },
    avatarSpeaking: {
      id: "avatarSpeaking",
      title: "数字人展示",
      type: "image",
      section: "Lychee-FD 驱动数字人与机器人效果图",
      tags: ["Demo of Digital Avatar", "对话状态"],
      enabled: true,
      src: "assets/images/avatar/avatar_speaking.png",
      width: 1024,
      height: 768,
      description: "展示数字人在接收语音、生成短反馈与自然接话时的表情状态变化。",
    },
    shennieRobot: {
      id: "shennieRobot",
      title: "Shennie 机器人展示",
      type: "image",
      section: "Lychee-FD 驱动数字人与机器人效果图",
      tags: ["Demo of Shennie Robot", "机器人交互"],
      enabled: true,
      src: "assets/images/avatar/shennie_robot.png",
      width: 1600,
      height: 900,
      description: "Lychee-FD 可作为机器人背后的对话交互模块，驱动机器人实现自然打断、附和反馈和实时响应。",
    },
    avatarDigitalDialogue: {
      id: "avatarDigitalDialogue",
      title: "Digital avatar demo 01",
      type: "reservedVideo",
      section: "Digital avatar demos",
      tags: [],
      enabled: true,
      posterMode: "firstFrame",
      previewPreload: "metadata",
      videoSources: ["assets/videos/digital-avatar-01.mp4?v=57"],
      videoWidth: 1080,
      videoHeight: 1920,
      description: "",
    },
    avatarDigitalFeedback: {
      id: "avatarDigitalFeedback",
      title: "Digital avatar demo 02",
      type: "reservedVideo",
      section: "Digital avatar demos",
      tags: [],
      enabled: true,
      posterMode: "firstFrame",
      previewPreload: "metadata",
      videoSources: ["assets/videos/digital-avatar-02.mp4?v=57"],
      videoWidth: 1080,
      videoHeight: 1920,
      description: "",
    },
    avatarDigitalExpression: {
      id: "avatarDigitalExpression",
      title: "Digital avatar demo 03",
      type: "reservedVideo",
      section: "Digital avatar demos",
      tags: [],
      enabled: true,
      posterMode: "firstFrame",
      previewPreload: "metadata",
      videoSources: ["assets/videos/digital-avatar-03.mp4?v=57"],
      videoWidth: 1080,
      videoHeight: 1920,
      description: "",
    },
    avatarRobotShennie: {
      id: "avatarRobotShennie",
      title: "Shennie robot demo 01",
      type: "reservedVideo",
      section: "Robot demos",
      tags: [],
      enabled: true,
      posterMode: "firstFrame",
      previewPreload: "metadata",
      videoSources: ["assets/videos/robot-demo-01.mp4"],
      videoWidth: 1080,
      videoHeight: 1920,
      description: "",
    },
    avatarRobotResponse: {
      id: "avatarRobotResponse",
      title: "Shennie robot demo 02",
      type: "reservedVideo",
      section: "Robot demos",
      tags: [],
      enabled: true,
      posterMode: "firstFrame",
      previewPreload: "metadata",
      videoSources: ["assets/videos/robot-demo-02.mp4"],
      videoWidth: 1080,
      videoHeight: 1920,
      description: "",
    },
    avatarRobotInteraction: {
      id: "avatarRobotInteraction",
      title: "Shennie robot demo 03",
      type: "reservedVideo",
      section: "Robot demos",
      tags: [],
      enabled: true,
      posterMode: "firstFrame",
      previewPreload: "metadata",
      videoSources: ["assets/videos/robot-demo-03.mp4"],
      videoWidth: 1080,
      videoHeight: 1920,
      description: "",
    },
  },

  assetGroups: {
    results: ["spokenQATable", "duplexBenchTable", "onlineMultistreamInference"],
    embodiedShowcase: [
      "avatarStatic",
      "avatarSpeaking",
      "shennieRobot",
    ],
    digitalAvatarVideos: [
      "avatarDigitalDialogue",
      "avatarDigitalFeedback",
      "avatarDigitalExpression",
    ],
    robotVideos: [
      "avatarRobotShennie",
      "avatarRobotResponse",
      "avatarRobotInteraction",
    ],
    embodiedVideos: [
      "avatarDigitalDialogue",
      "avatarDigitalFeedback",
      "avatarDigitalExpression",
      "avatarRobotShennie",
      "avatarRobotResponse",
      "avatarRobotInteraction",
    ],
    embodied: [
      "avatarStatic",
      "avatarSpeaking",
      "shennieRobot",
      "avatarDigitalDialogue",
      "avatarDigitalFeedback",
      "avatarDigitalExpression",
      "avatarRobotShennie",
      "avatarRobotResponse",
      "avatarRobotInteraction",
    ],
  },

  demoCases: [
    {
      id: "demo_user_backchannel",
      displayIndex: "01",
      category: "策略攻防",
      type: "discussion",
      title: "AI Product Strategy Challenge",
      subtitle: "A multi-turn debate around growth and retention where the system maintains its stance, tracks context, and keeps responding through frequent interruptions.",
      tags: ["高频打断", "观点攻防", "多轮追踪"],
      videoSources: ["assets/videos/demo-ai-product-comment.mp4"],
      poster: "assets/images/demo/demo01.png",
      videoWidth: 1728,
      videoHeight: 1080,
      posterWidth: 960,
      posterHeight: 600,
      scene: "策略攻防",
      highlight: "即使用户不断反驳和插话，系统依然能够围绕核心议题持续推理，保持回应稳定。",
    },
    {
      id: "demo_user_strategy",
      displayIndex: "02",
      category: "策略辩论",
      type: "strategy",
      title: "Growth and Retention Strategy Debate",
      subtitle: "The user repeatedly probes whether a new product should prioritize growth, while the system quickly resumes its argument after interruptions and keeps its reasoning coherent.",
      tags: ["快速接回", "上下文跟踪", "多轮辩论"],
      videoSources: ["assets/videos/demo-user-strategy.mp4"],
      poster: "assets/images/demo/demo02.png",
      videoWidth: 1728,
      videoHeight: 1080,
      posterWidth: 960,
      posterHeight: 600,
      scene: "策略辩论",
      highlight: "在连续追问和观点攻防中，系统能够理解用户反驳重点，并围绕增长与留存持续展开分析。",
    },
    {
      id: "demo_cook_beef",
      displayIndex: "03",
      category: "厨房助手",
      type: "handsfree",
      title: "Real-Time Cooking Assistant",
      subtitle: "While the user cooks and asks for the next step, the system combines the current ingredients and kitchen context to provide actionable guidance quickly.",
      tags: ["免手交互", "实时追问", "即时修正"],
      videoSources: ["assets/videos/demo-cooking-beef.mp4"],
      poster: "assets/images/demo/demo03.png",
      videoWidth: 1728,
      videoHeight: 1080,
      posterWidth: 960,
      posterHeight: 540,
      scene: "厨房助手",
      highlight: "在双手忙碌的厨房场景中，系统能够边听边答，持续辅助用户完成烹饪流程。",
    },
  ],
};
